### ISSUE TITLE
USB Keyboard can't be used to flash fpga updates

### ISSUE THREAD

**Issue by randyrossi** [DrZingo/Ultimate64-manual-unofficial#1]
Something to add to your issues section:

I noticed that the screen that prompts you with the 'Flash now? YES NO'  after the ultimate verifies your update file (i.e. update_10B.u64) , won't work with a USB keyboard.  It only lets you use cursor/enter with a real C64 keyboard.  This is kind of strange since you can navigate to your file and use all other menu functions with a USB keyboard right up until that flash confirmation prompt.  At least that's my experience with 1.06.  It may have been fixed in 1.0B.

**Comment by DrZingo** [comment]
Thanks. 
I have no intention to continue on this documentation, as I am now working on the official one. Most of the issues mentioned in this one is already solved anyway.  
Please have a look at the official documentation here: 
https://1541u-documentation.readthedocs.io/en/latest/
